# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OwnerResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, safes: List[str]=None):  # noqa: E501
        """OwnerResponse - a model defined in Swagger

        :param safes: The safes of this OwnerResponse.  # noqa: E501
        :type safes: List[str]
        """
        self.swagger_types = {
            'safes': List[str]
        }

        self.attribute_map = {
            'safes': 'safes'
        }

        self._safes = safes

    @classmethod
    def from_dict(cls, dikt) -> 'OwnerResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OwnerResponse of this OwnerResponse.  # noqa: E501
        :rtype: OwnerResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def safes(self) -> List[str]:
        """Gets the safes of this OwnerResponse.


        :return: The safes of this OwnerResponse.
        :rtype: List[str]
        """
        return self._safes

    @safes.setter
    def safes(self, safes: List[str]):
        """Sets the safes of this OwnerResponse.


        :param safes: The safes of this OwnerResponse.
        :type safes: List[str]
        """
        if safes is None:
            raise ValueError("Invalid value for `safes`, must not be `None`")  # noqa: E501

        self._safes = safes
