# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SafeMultisigConfirmation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, signature: str=None):  # noqa: E501
        """SafeMultisigConfirmation - a model defined in Swagger

        :param signature: The signature of this SafeMultisigConfirmation.  # noqa: E501
        :type signature: str
        """
        self.swagger_types = {
            'signature': str
        }

        self.attribute_map = {
            'signature': 'signature'
        }

        self._signature = signature

    @classmethod
    def from_dict(cls, dikt) -> 'SafeMultisigConfirmation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SafeMultisigConfirmation of this SafeMultisigConfirmation.  # noqa: E501
        :rtype: SafeMultisigConfirmation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> str:
        """Gets the signature of this SafeMultisigConfirmation.


        :return: The signature of this SafeMultisigConfirmation.
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature: str):
        """Sets the signature of this SafeMultisigConfirmation.


        :param signature: The signature of this SafeMultisigConfirmation.
        :type signature: str
        """
        if signature is None:
            raise ValueError("Invalid value for `signature`, must not be `None`")  # noqa: E501

        self._signature = signature
