# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SafeModuleTransactionResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, created: datetime=None, execution_date: datetime=None, block_number: int=None, transaction_hash: str=None, safe: str=None, module: str=None, to: str=None, value: str=None, data: str=None, operation: int=None, data_decoded: str=None):  # noqa: E501
        """SafeModuleTransactionResponse - a model defined in Swagger

        :param created: The created of this SafeModuleTransactionResponse.  # noqa: E501
        :type created: datetime
        :param execution_date: The execution_date of this SafeModuleTransactionResponse.  # noqa: E501
        :type execution_date: datetime
        :param block_number: The block_number of this SafeModuleTransactionResponse.  # noqa: E501
        :type block_number: int
        :param transaction_hash: The transaction_hash of this SafeModuleTransactionResponse.  # noqa: E501
        :type transaction_hash: str
        :param safe: The safe of this SafeModuleTransactionResponse.  # noqa: E501
        :type safe: str
        :param module: The module of this SafeModuleTransactionResponse.  # noqa: E501
        :type module: str
        :param to: The to of this SafeModuleTransactionResponse.  # noqa: E501
        :type to: str
        :param value: The value of this SafeModuleTransactionResponse.  # noqa: E501
        :type value: str
        :param data: The data of this SafeModuleTransactionResponse.  # noqa: E501
        :type data: str
        :param operation: The operation of this SafeModuleTransactionResponse.  # noqa: E501
        :type operation: int
        :param data_decoded: The data_decoded of this SafeModuleTransactionResponse.  # noqa: E501
        :type data_decoded: str
        """
        self.swagger_types = {
            'created': datetime,
            'execution_date': datetime,
            'block_number': int,
            'transaction_hash': str,
            'safe': str,
            'module': str,
            'to': str,
            'value': str,
            'data': str,
            'operation': int,
            'data_decoded': str
        }

        self.attribute_map = {
            'created': 'created',
            'execution_date': 'executionDate',
            'block_number': 'blockNumber',
            'transaction_hash': 'transactionHash',
            'safe': 'safe',
            'module': 'module',
            'to': 'to',
            'value': 'value',
            'data': 'data',
            'operation': 'operation',
            'data_decoded': 'dataDecoded'
        }

        self._created = created
        self._execution_date = execution_date
        self._block_number = block_number
        self._transaction_hash = transaction_hash
        self._safe = safe
        self._module = module
        self._to = to
        self._value = value
        self._data = data
        self._operation = operation
        self._data_decoded = data_decoded

    @classmethod
    def from_dict(cls, dikt) -> 'SafeModuleTransactionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SafeModuleTransactionResponse of this SafeModuleTransactionResponse.  # noqa: E501
        :rtype: SafeModuleTransactionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created(self) -> datetime:
        """Gets the created of this SafeModuleTransactionResponse.


        :return: The created of this SafeModuleTransactionResponse.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created: datetime):
        """Sets the created of this SafeModuleTransactionResponse.


        :param created: The created of this SafeModuleTransactionResponse.
        :type created: datetime
        """

        self._created = created

    @property
    def execution_date(self) -> datetime:
        """Gets the execution_date of this SafeModuleTransactionResponse.


        :return: The execution_date of this SafeModuleTransactionResponse.
        :rtype: datetime
        """
        return self._execution_date

    @execution_date.setter
    def execution_date(self, execution_date: datetime):
        """Sets the execution_date of this SafeModuleTransactionResponse.


        :param execution_date: The execution_date of this SafeModuleTransactionResponse.
        :type execution_date: datetime
        """
        if execution_date is None:
            raise ValueError("Invalid value for `execution_date`, must not be `None`")  # noqa: E501

        self._execution_date = execution_date

    @property
    def block_number(self) -> int:
        """Gets the block_number of this SafeModuleTransactionResponse.


        :return: The block_number of this SafeModuleTransactionResponse.
        :rtype: int
        """
        return self._block_number

    @block_number.setter
    def block_number(self, block_number: int):
        """Sets the block_number of this SafeModuleTransactionResponse.


        :param block_number: The block_number of this SafeModuleTransactionResponse.
        :type block_number: int
        """

        self._block_number = block_number

    @property
    def transaction_hash(self) -> str:
        """Gets the transaction_hash of this SafeModuleTransactionResponse.


        :return: The transaction_hash of this SafeModuleTransactionResponse.
        :rtype: str
        """
        return self._transaction_hash

    @transaction_hash.setter
    def transaction_hash(self, transaction_hash: str):
        """Sets the transaction_hash of this SafeModuleTransactionResponse.


        :param transaction_hash: The transaction_hash of this SafeModuleTransactionResponse.
        :type transaction_hash: str
        """

        self._transaction_hash = transaction_hash

    @property
    def safe(self) -> str:
        """Gets the safe of this SafeModuleTransactionResponse.


        :return: The safe of this SafeModuleTransactionResponse.
        :rtype: str
        """
        return self._safe

    @safe.setter
    def safe(self, safe: str):
        """Sets the safe of this SafeModuleTransactionResponse.


        :param safe: The safe of this SafeModuleTransactionResponse.
        :type safe: str
        """
        if safe is None:
            raise ValueError("Invalid value for `safe`, must not be `None`")  # noqa: E501
        if safe is not None and len(safe) > 42:
            raise ValueError("Invalid value for `safe`, length must be less than or equal to `42`")  # noqa: E501
        if safe is not None and len(safe) < 1:
            raise ValueError("Invalid value for `safe`, length must be greater than or equal to `1`")  # noqa: E501

        self._safe = safe

    @property
    def module(self) -> str:
        """Gets the module of this SafeModuleTransactionResponse.


        :return: The module of this SafeModuleTransactionResponse.
        :rtype: str
        """
        return self._module

    @module.setter
    def module(self, module: str):
        """Sets the module of this SafeModuleTransactionResponse.


        :param module: The module of this SafeModuleTransactionResponse.
        :type module: str
        """
        if module is None:
            raise ValueError("Invalid value for `module`, must not be `None`")  # noqa: E501
        if module is not None and len(module) > 42:
            raise ValueError("Invalid value for `module`, length must be less than or equal to `42`")  # noqa: E501
        if module is not None and len(module) < 1:
            raise ValueError("Invalid value for `module`, length must be greater than or equal to `1`")  # noqa: E501

        self._module = module

    @property
    def to(self) -> str:
        """Gets the to of this SafeModuleTransactionResponse.


        :return: The to of this SafeModuleTransactionResponse.
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to: str):
        """Sets the to of this SafeModuleTransactionResponse.


        :param to: The to of this SafeModuleTransactionResponse.
        :type to: str
        """
        if to is None:
            raise ValueError("Invalid value for `to`, must not be `None`")  # noqa: E501
        if to is not None and len(to) > 42:
            raise ValueError("Invalid value for `to`, length must be less than or equal to `42`")  # noqa: E501
        if to is not None and len(to) < 1:
            raise ValueError("Invalid value for `to`, length must be greater than or equal to `1`")  # noqa: E501

        self._to = to

    @property
    def value(self) -> str:
        """Gets the value of this SafeModuleTransactionResponse.


        :return: The value of this SafeModuleTransactionResponse.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this SafeModuleTransactionResponse.


        :param value: The value of this SafeModuleTransactionResponse.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def data(self) -> str:
        """Gets the data of this SafeModuleTransactionResponse.


        :return: The data of this SafeModuleTransactionResponse.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this SafeModuleTransactionResponse.


        :param data: The data of this SafeModuleTransactionResponse.
        :type data: str
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def operation(self) -> int:
        """Gets the operation of this SafeModuleTransactionResponse.


        :return: The operation of this SafeModuleTransactionResponse.
        :rtype: int
        """
        return self._operation

    @operation.setter
    def operation(self, operation: int):
        """Sets the operation of this SafeModuleTransactionResponse.


        :param operation: The operation of this SafeModuleTransactionResponse.
        :type operation: int
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    @property
    def data_decoded(self) -> str:
        """Gets the data_decoded of this SafeModuleTransactionResponse.


        :return: The data_decoded of this SafeModuleTransactionResponse.
        :rtype: str
        """
        return self._data_decoded

    @data_decoded.setter
    def data_decoded(self, data_decoded: str):
        """Sets the data_decoded of this SafeModuleTransactionResponse.


        :param data_decoded: The data_decoded of this SafeModuleTransactionResponse.
        :type data_decoded: str
        """

        self._data_decoded = data_decoded
