# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TokenInfoResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, address: str=None, name: str=None, symbol: str=None, decimals: int=None, logo_uri: str=None):  # noqa: E501
        """TokenInfoResponse - a model defined in Swagger

        :param type: The type of this TokenInfoResponse.  # noqa: E501
        :type type: str
        :param address: The address of this TokenInfoResponse.  # noqa: E501
        :type address: str
        :param name: The name of this TokenInfoResponse.  # noqa: E501
        :type name: str
        :param symbol: The symbol of this TokenInfoResponse.  # noqa: E501
        :type symbol: str
        :param decimals: The decimals of this TokenInfoResponse.  # noqa: E501
        :type decimals: int
        :param logo_uri: The logo_uri of this TokenInfoResponse.  # noqa: E501
        :type logo_uri: str
        """
        self.swagger_types = {
            'type': str,
            'address': str,
            'name': str,
            'symbol': str,
            'decimals': int,
            'logo_uri': str
        }

        self.attribute_map = {
            'type': 'type',
            'address': 'address',
            'name': 'name',
            'symbol': 'symbol',
            'decimals': 'decimals',
            'logo_uri': 'logoUri'
        }

        self._type = type
        self._address = address
        self._name = name
        self._symbol = symbol
        self._decimals = decimals
        self._logo_uri = logo_uri

    @classmethod
    def from_dict(cls, dikt) -> 'TokenInfoResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TokenInfoResponse of this TokenInfoResponse.  # noqa: E501
        :rtype: TokenInfoResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this TokenInfoResponse.


        :return: The type of this TokenInfoResponse.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this TokenInfoResponse.


        :param type: The type of this TokenInfoResponse.
        :type type: str
        """

        self._type = type

    @property
    def address(self) -> str:
        """Gets the address of this TokenInfoResponse.


        :return: The address of this TokenInfoResponse.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this TokenInfoResponse.


        :param address: The address of this TokenInfoResponse.
        :type address: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def name(self) -> str:
        """Gets the name of this TokenInfoResponse.


        :return: The name of this TokenInfoResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TokenInfoResponse.


        :param name: The name of this TokenInfoResponse.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def symbol(self) -> str:
        """Gets the symbol of this TokenInfoResponse.


        :return: The symbol of this TokenInfoResponse.
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol: str):
        """Sets the symbol of this TokenInfoResponse.


        :param symbol: The symbol of this TokenInfoResponse.
        :type symbol: str
        """
        if symbol is None:
            raise ValueError("Invalid value for `symbol`, must not be `None`")  # noqa: E501
        if symbol is not None and len(symbol) < 1:
            raise ValueError("Invalid value for `symbol`, length must be greater than or equal to `1`")  # noqa: E501

        self._symbol = symbol

    @property
    def decimals(self) -> int:
        """Gets the decimals of this TokenInfoResponse.


        :return: The decimals of this TokenInfoResponse.
        :rtype: int
        """
        return self._decimals

    @decimals.setter
    def decimals(self, decimals: int):
        """Sets the decimals of this TokenInfoResponse.


        :param decimals: The decimals of this TokenInfoResponse.
        :type decimals: int
        """
        if decimals is None:
            raise ValueError("Invalid value for `decimals`, must not be `None`")  # noqa: E501

        self._decimals = decimals

    @property
    def logo_uri(self) -> str:
        """Gets the logo_uri of this TokenInfoResponse.


        :return: The logo_uri of this TokenInfoResponse.
        :rtype: str
        """
        return self._logo_uri

    @logo_uri.setter
    def logo_uri(self, logo_uri: str):
        """Sets the logo_uri of this TokenInfoResponse.


        :param logo_uri: The logo_uri of this TokenInfoResponse.
        :type logo_uri: str
        """

        self._logo_uri = logo_uri
